version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: GymDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: master
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_core_gym_app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/GymDB
      DB_USERNAME: postgres
      DB_PASSWORD: master
    depends_on:
      - postgres

volumes:
  postgres_data:
