spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  web:
    resources:
      add-mappings: true
  application:
    name: SPRING-CORE-GYM

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      hikari: true
  prometheus:
    metrics:
      export:
        enabled: true

token:
  signing:
    key: 63B74F4E1D5F0B2C4A3F2E685F7A1C534D7E357E1D7F5C3B495C734B64327844

max:
  login:
    attempt: 3

logout:
  duration:
    minutes: 5

expiration:
  date:
    milliseconds: 900000

server:
  ssl:
    enabled: true
    key-store: classpath:myCertificate.jks
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
    trust-store: classpath:myCertificate.jks
    trust-store-type: PKCS12
    trust-store-password: ${TRUST_STORE_PASSWORD}
  port: 8443

logging:
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{X-Transaction-Id}] [%thread] %-5level %logger{36} - %msg%n"

eureka:
  client:
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: https://172.18.0.10:8761/eureka/
    tls:
      enabled: true
      key-store: classpath:myCertificate.jks
      key-store-type: PKCS12
      key-store-password: ${KEY_STORE_PASSWORD}
      key-password: ${KEY_STORE_PASSWORD}
      trust-store: classpath:myCertificate.jks
      trust-store-type: PKCS12
      trust-store-password: ${TRUST_STORE_PASSWORD}
  instance:
    hostname: localhost

resilience4j:
  circuitbreaker:
    instances:
      changeWorkloadCircuitBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      changeWorkloadRetry:
        max-attempts: 3
        wait-duration: 2s
        enable-randomized-wait: true
